# Generated by Django 5.2.8 on 2025-11-25 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_control_calidad', models.CharField(blank=True, max_length=50, unique=True)),
                ('resultado', models.CharField(max_length=255)),
                ('fecha_verificacion', models.DateField()),
                ('aprobado', models.BooleanField(default=False)),
                ('firma_inspector', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JefeProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('firma', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JefeSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('firma', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialEnvasePrimario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch', models.CharField(max_length=100)),
                ('control_calidad', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad_teorica', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_real', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rendimiento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanillaEnvasePrimario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('usuario_creacion', models.CharField(blank=True, max_length=100, verbose_name='Usuario creador')),
                ('fecha_primera_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Primera modificación')),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('usuario_ultima_modificacion', models.CharField(blank=True, max_length=100, verbose_name='Último usuario que modificó')),
                ('serie', models.CharField(blank=True, max_length=50)),
                ('numero_planilla', models.CharField(blank=True, max_length=50)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('rendimiento_teorico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_estuches', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodo_eficacia', models.IntegerField(help_text='Meses')),
                ('materiales_json', models.JSONField(blank=True, default=list, help_text="Lista de materiales en formato JSON: [{'material': 'Envase', 'batch': 'B001', 'cantidad': 100}]")),
                ('verificado_por_qf', models.CharField(blank=True, max_length=255)),
                ('registro_isp', models.CharField(blank=True, max_length=100)),
                ('batch_standard', models.CharField(blank=True, max_length=100)),
                ('control_calidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.controlcalidad')),
                ('jefe_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.jefeproduccion')),
                ('jefe_seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.jefeseccion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.producto')),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.tipoproducto')),
            ],
            options={
                'verbose_name': 'Planilla Envase Primario',
                'verbose_name_plural': 'Planillas Envase Primario',
            },
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.producto'),
        ),
        migrations.CreateModel(
            name='PlanillaFabricacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('usuario_creacion', models.CharField(blank=True, max_length=100, verbose_name='Usuario creador')),
                ('fecha_primera_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Primera modificación')),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('usuario_ultima_modificacion', models.CharField(blank=True, max_length=100, verbose_name='Último usuario que modificó')),
                ('serie', models.CharField(max_length=50)),
                ('numero_planilla', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('rendimiento_teorico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodo_eficacia', models.IntegerField()),
                ('cantidad_estuches', models.DecimalField(decimal_places=2, max_digits=10)),
                ('registro_isp', models.CharField(blank=True, max_length=100)),
                ('batch_standard', models.TextField(blank=True)),
                ('cont_x_100ml', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('peso_firma', models.TextField(blank=True)),
                ('controlo_firma', models.TextField(blank=True)),
                ('verificado_por_qf', models.TextField(blank=True)),
                ('sala_pesaje', models.CharField(blank=True, max_length=50)),
                ('balanza_numero', models.CharField(blank=True, max_length=50)),
                ('liberacion_area', models.BooleanField(default=False)),
                ('etiqueta_limpieza', models.BooleanField(default=False)),
                ('control_calidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planillas', to='GPQAPI.controlcalidad')),
                ('jefe_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planillas_produccion', to='GPQAPI.jefeproduccion')),
                ('jefe_seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planillas_seccion', to='GPQAPI.jefeseccion')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.materiaprima')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.producto')),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.tipoproducto')),
            ],
            options={
                'verbose_name': 'Planilla de Fabricación',
                'verbose_name_plural': 'Planillas de Fabricación',
            },
        ),
        migrations.CreateModel(
            name='PlanillaEnvase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('usuario_creacion', models.CharField(blank=True, max_length=100, verbose_name='Usuario creador')),
                ('fecha_primera_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Primera modificación')),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('usuario_ultima_modificacion', models.CharField(blank=True, max_length=100, verbose_name='Último usuario que modificó')),
                ('cantidad_teorica', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_real', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rendimiento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('firma_jefe_seccion', models.CharField(max_length=255)),
                ('firma_jefe_produccion', models.CharField(max_length=255)),
                ('jefe_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.jefeproduccion')),
                ('jefe_seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.jefeseccion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.producto')),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.tipoproducto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialEnvaseDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_entregada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Entregada')),
                ('batch_material', models.CharField(blank=True, max_length=100, verbose_name='Batch del Material')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.materialenvaseprimario')),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.planillaenvaseprimario')),
            ],
            options={
                'verbose_name': 'Detalle Material Envase',
                'verbose_name_plural': 'Detalles Materiales Envase',
                'unique_together': {('planilla', 'material')},
            },
        ),
    ]
