# Generated by Django 5.2.8 on 2025-11-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materialenvasedetalle',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='materialenvasedetalle',
            name='material',
        ),
        migrations.RemoveField(
            model_name='materialenvasedetalle',
            name='planilla',
        ),
        migrations.AlterField(
            model_name='planillaenvaseprimario',
            name='batch_standard',
            field=models.CharField(blank=True, max_length=100, verbose_name='Batch Standard'),
        ),
        migrations.AlterField(
            model_name='planillaenvaseprimario',
            name='materiales_json',
            field=models.JSONField(blank=True, default=list, help_text='Lista de materiales en formato JSON'),
        ),
        migrations.AlterField(
            model_name='planillaenvaseprimario',
            name='registro_isp',
            field=models.CharField(blank=True, max_length=100, verbose_name='Registro ISP'),
        ),
        migrations.AlterField(
            model_name='planillaenvaseprimario',
            name='rendimiento_teorico',
            field=models.DecimalField(decimal_places=2, help_text='En litros', max_digits=10),
        ),
        migrations.AlterField(
            model_name='planillaenvaseprimario',
            name='verificado_por_qf',
            field=models.CharField(blank=True, max_length=255, verbose_name='Verificado por Q.F.'),
        ),
        migrations.DeleteModel(
            name='MaterialEnvasePrimario',
        ),
        migrations.DeleteModel(
            name='MaterialEnvaseDetalle',
        ),
    ]
