# Generated by Django 5.2.8 on 2025-11-25 22:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0002_alter_materialenvasedetalle_unique_together_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('permisos', models.JSONField(default=list, help_text='Lista de permisos en formato JSON')),
            ],
        ),
        migrations.RemoveField(
            model_name='planillaenvase',
            name='jefe_produccion',
        ),
        migrations.RemoveField(
            model_name='planillafabricacion',
            name='jefe_produccion',
        ),
        migrations.RemoveField(
            model_name='planillaenvaseprimario',
            name='jefe_produccion',
        ),
        migrations.RemoveField(
            model_name='planillaenvaseprimario',
            name='jefe_seccion',
        ),
        migrations.RemoveField(
            model_name='planillafabricacion',
            name='jefe_seccion',
        ),
        migrations.RemoveField(
            model_name='planillaenvase',
            name='jefe_seccion',
        ),
        migrations.AddField(
            model_name='planillaenvase',
            name='firma_jefe_produccion_texto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='planillaenvase',
            name='firma_jefe_seccion_texto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='RegistroFirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_firma', models.CharField(choices=[('JEFE_SECCION', 'Jefe de Sección'), ('JEFE_PRODUCCION', 'Jefe de Producción'), ('INSPECTOR_CALIDAD', 'Inspector de Calidad'), ('QUIMICO_FARMACEUTICO', 'Químico Farmacéutico')], max_length=50)),
                ('firma_hash', models.CharField(help_text='Hash de la firma digital', max_length=255)),
                ('timestamp_firma', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('EXPIRADA', 'Expirada')], default='PENDIENTE', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('codigo_verificacion', models.CharField(blank=True, max_length=6)),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('planilla_envase_primario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.planillaenvaseprimario')),
                ('planilla_fabricacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.planillafabricacion')),
            ],
            options={
                'verbose_name': 'Registro de Firma',
                'verbose_name_plural': 'Registros de Firmas',
            },
        ),
        migrations.AddField(
            model_name='planillaenvaseprimario',
            name='firma_jefe_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas_jefe_produccion_envase_primario', to='GPQAPI.registrofirma'),
        ),
        migrations.AddField(
            model_name='planillaenvaseprimario',
            name='firma_jefe_seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas_jefe_seccion_envase_primario', to='GPQAPI.registrofirma'),
        ),
        migrations.AddField(
            model_name='planillaenvaseprimario',
            name='firma_quimico_farmaceutico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas_quimico_farmaceutico', to='GPQAPI.registrofirma'),
        ),
        migrations.AddField(
            model_name='planillafabricacion',
            name='firma_inspector_calidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas_inspector_fabricacion', to='GPQAPI.registrofirma'),
        ),
        migrations.AddField(
            model_name='planillafabricacion',
            name='firma_jefe_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas_jefe_produccion_fabricacion', to='GPQAPI.registrofirma'),
        ),
        migrations.AddField(
            model_name='planillafabricacion',
            name='firma_jefe_seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas_jefe_seccion_fabricacion', to='GPQAPI.registrofirma'),
        ),
        migrations.AlterField(
            model_name='planillaenvase',
            name='firma_jefe_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas_jefe_produccion_envase', to='GPQAPI.registrofirma'),
        ),
        migrations.AlterField(
            model_name='planillaenvase',
            name='firma_jefe_seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas_jefe_seccion_envase', to='GPQAPI.registrofirma'),
        ),
        migrations.CreateModel(
            name='UsuarioPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('firma_digital', models.TextField(blank=True)),
                ('fecha_vencimiento_credenciales', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='registrofirma',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('numero_licencia', models.CharField(blank=True, max_length=50)),
                ('firma_imagen', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=100)),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=15)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.rol')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='JefeProduccion',
        ),
        migrations.DeleteModel(
            name='JefeSeccion',
        ),
    ]
