# Generated by Django 5.2.8 on 2025-11-25 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0003_rol_remove_planillaenvase_jefe_produccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='firma_imagen',
        ),
    ]
