# Generated by Django 5.2.8 on 2025-11-25 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0004_remove_perfilusuario_firma_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente_firmas', '🟡 Pendiente de Firmas'), ('pendiente_jefe_produccion', '🔵 Esperando Jefe Producción'), ('aprobada', '✅ Aprobada')], default='pendiente_firmas', max_length=30)),
                ('creado_por', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FirmaPlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_firma', models.CharField(choices=[('jefe_seccion', 'Jefe de Sección'), ('jefe_produccion', 'Jefe de Producción')], max_length=20)),
                ('rut', models.CharField(max_length=12)),
                ('firma_digital', models.TextField()),
                ('fecha_firma', models.DateTimeField(auto_now_add=True)),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmas_relacion', to='GPQAPI.planilla')),
            ],
            options={
                'unique_together': {('planilla', 'tipo_firma')},
            },
        ),
    ]
