# Generated by Django 5.2.8 on 2025-11-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0005_planilla_firmaplanilla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planillaenvaseprimario',
            name='verificado_por_qf',
        ),
        migrations.RemoveField(
            model_name='planillafabricacion',
            name='verificado_por_qf',
        ),
        migrations.AddField(
            model_name='planillaenvaseprimario',
            name='verificado_por',
            field=models.CharField(blank=True, max_length=255, verbose_name='Verificado por Químico Farmacéutico'),
        ),
        migrations.AddField(
            model_name='planillafabricacion',
            name='verificado_por',
            field=models.TextField(blank=True, verbose_name='Verificado por Químico Farmacéutico'),
        ),
    ]
