# Generated by Django 5.2.8 on 2025-11-25 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0006_remove_planillaenvaseprimario_verificado_por_qf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilla',
            name='planilla_relacionada_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planilla',
            name='tipo_planilla',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='planillaenvase',
            name='planilla_firmas',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planilla_envase_rel', to='GPQAPI.planilla'),
        ),
        migrations.AddField(
            model_name='planillaenvaseprimario',
            name='planilla_firmas',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planilla_envase_primario_rel', to='GPQAPI.planilla'),
        ),
        migrations.AddField(
            model_name='planillafabricacion',
            name='planilla_firmas',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planilla_fabricacion_rel', to='GPQAPI.planilla'),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='estado',
            field=models.CharField(choices=[('pendiente_firmas', ' Pendiente de Firmas'), ('pendiente_jefe_produccion', ' Esperando Jefe Producción'), ('aprobada', ' Aprobada')], default='pendiente_firmas', max_length=30),
        ),
    ]
