# Generated by Django 5.2.8 on 2025-11-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0007_planilla_planilla_relacionada_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planilla',
            name='planilla_relacionada_id',
        ),
        migrations.AddField(
            model_name='firmaplanilla',
            name='nombre_firmante',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='planilla',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción automática de la planilla'),
        ),
        migrations.AddField(
            model_name='planilla',
            name='planilla_relacionada_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='creado_por',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='estado',
            field=models.CharField(choices=[('pendiente_ambas', '🟡 Pendiente de Ambas Firmas'), ('pendiente_jefe_seccion', '🔵 Esperando Jefe Sección'), ('pendiente_jefe_produccion', '🟠 Esperando Jefe Producción'), ('aprobada', '✅ Aprobada')], default='pendiente_ambas', max_length=30),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='numero',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
