# Generated by Django 5.2.8 on 2025-11-26 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0008_remove_planilla_planilla_relacionada_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planillaenvaseprimario',
            name='verificado_por',
        ),
    ]
