# Generated by Django 5.2.8 on 2025-11-26 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0009_remove_planillaenvaseprimario_verificado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlcalidad',
            name='firma_inspector',
        ),
        migrations.RemoveField(
            model_name='registrofirma',
            name='intentos_fallidos',
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='firma_control_calidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas_control_calidad', to='GPQAPI.registrofirma'),
        ),
        migrations.AddField(
            model_name='registrofirma',
            name='control_calidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.controlcalidad'),
        ),
        migrations.AlterField(
            model_name='registrofirma',
            name='tipo_firma',
            field=models.CharField(choices=[('JEFE_SECCION', 'Jefe de Sección'), ('JEFE_PRODUCCION', 'Jefe de Producción'), ('INSPECTOR_CALIDAD', 'Inspector de Calidad'), ('QUIMICO_FARMACEUTICO', 'Químico Farmacéutico'), ('CONTROL_CALIDAD', 'Control de Calidad')], max_length=50),
        ),
    ]
