# Generated by Django 5.2.8 on 2025-11-26 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0010_remove_controlcalidad_firma_inspector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planillafabricacion',
            name='planilla_firmas',
        ),
        migrations.RemoveField(
            model_name='planillaenvaseprimario',
            name='planilla_firmas',
        ),
        migrations.RemoveField(
            model_name='planillaenvase',
            name='planilla_firmas',
        ),
        migrations.AlterField(
            model_name='planillafabricacion',
            name='control_calidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planillas_fabricacion', to='GPQAPI.controlcalidad'),
        ),
        migrations.DeleteModel(
            name='FirmaPlanilla',
        ),
        migrations.DeleteModel(
            name='Planilla',
        ),
    ]
