# Generated by Django 5.2.8 on 2025-11-26 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0011_remove_planillafabricacion_planilla_firmas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jarabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('planilla_envase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jarabe', to='GPQAPI.planillaenvase')),
                ('planilla_envase_primario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jarabe', to='GPQAPI.planillaenvaseprimario')),
                ('planilla_fabricacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jarabe', to='GPQAPI.planillafabricacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.producto')),
            ],
            options={
                'verbose_name': 'Jarabe',
                'verbose_name_plural': 'Jarabes',
            },
        ),
    ]
