# Generated by Django 5.2.8 on 2025-11-26 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0012_jarabe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jarabe',
            options={},
        ),
        migrations.AlterModelOptions(
            name='planillaenvaseprimario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='planillafabricacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='registrofirma',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuariopersonalizado',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='planillaenvase',
            name='firma_jefe_produccion_texto',
        ),
        migrations.RemoveField(
            model_name='planillaenvase',
            name='firma_jefe_seccion_texto',
        ),
        migrations.RemoveField(
            model_name='planillaenvaseprimario',
            name='batch_standard',
        ),
        migrations.RemoveField(
            model_name='planillaenvaseprimario',
            name='registro_isp',
        ),
        migrations.RemoveField(
            model_name='planillafabricacion',
            name='batch_standard',
        ),
        migrations.RemoveField(
            model_name='planillafabricacion',
            name='cont_x_100ml',
        ),
        migrations.RemoveField(
            model_name='planillafabricacion',
            name='controlo_firma',
        ),
        migrations.RemoveField(
            model_name='planillafabricacion',
            name='peso_firma',
        ),
        migrations.RemoveField(
            model_name='planillafabricacion',
            name='registro_isp',
        ),
        migrations.RemoveField(
            model_name='planillafabricacion',
            name='verificado_por',
        ),
        migrations.RemoveField(
            model_name='registrofirma',
            name='estado',
        ),
        migrations.AddField(
            model_name='planillafabricacion',
            name='firma_quimico_farmaceutico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firma_qf_fabricacion', to='GPQAPI.registrofirma'),
        ),
        migrations.AlterField(
            model_name='controlcalidad',
            name='firma_control_calidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas_cc', to='GPQAPI.registrofirma'),
        ),
        migrations.AlterField(
            model_name='jarabe',
            name='planilla_envase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GPQAPI.planillaenvase'),
        ),
        migrations.AlterField(
            model_name='jarabe',
            name='planilla_envase_primario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GPQAPI.planillaenvaseprimario'),
        ),
        migrations.AlterField(
            model_name='jarabe',
            name='planilla_fabricacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GPQAPI.planillafabricacion'),
        ),
        migrations.AlterField(
            model_name='planillaenvase',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='planillaenvase',
            name='fecha_primera_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planillaenvase',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='planillaenvase',
            name='firma_jefe_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firma_jp_envase', to='GPQAPI.registrofirma'),
        ),
        migrations.AlterField(
            model_name='planillaenvase',
            name='firma_jefe_seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firma_js_envase', to='GPQAPI.registrofirma'),
        ),
        migrations.AlterField(
            model_name='planillaenvase',
            name='usuario_creacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='planillaenvase',
            name='usuario_ultima_modificacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='planillaenvaseprimario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='planillaenvaseprimario',
            name='fecha_primera_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planillaenvaseprimario',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='planillaenvaseprimario',
            name='firma_jefe_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firma_jp_envase_primario', to='GPQAPI.registrofirma'),
        ),
        migrations.AlterField(
            model_name='planillaenvaseprimario',
            name='firma_jefe_seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firma_js_envase_primario', to='GPQAPI.registrofirma'),
        ),
        migrations.AlterField(
            model_name='planillaenvaseprimario',
            name='firma_quimico_farmaceutico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firma_qf_envase_primario', to='GPQAPI.registrofirma'),
        ),
        migrations.AlterField(
            model_name='planillaenvaseprimario',
            name='materiales_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='planillaenvaseprimario',
            name='numero_planilla',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='planillaenvaseprimario',
            name='periodo_eficacia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='planillaenvaseprimario',
            name='rendimiento_teorico',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='planillaenvaseprimario',
            name='serie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='planillaenvaseprimario',
            name='usuario_creacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='planillaenvaseprimario',
            name='usuario_ultima_modificacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='planillafabricacion',
            name='balanza_numero',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='planillafabricacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='planillafabricacion',
            name='fecha_primera_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planillafabricacion',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='planillafabricacion',
            name='firma_inspector_calidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firma_ic_fabricacion', to='GPQAPI.registrofirma'),
        ),
        migrations.AlterField(
            model_name='planillafabricacion',
            name='firma_jefe_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firma_jp_fabricacion', to='GPQAPI.registrofirma'),
        ),
        migrations.AlterField(
            model_name='planillafabricacion',
            name='firma_jefe_seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firma_js_fabricacion', to='GPQAPI.registrofirma'),
        ),
        migrations.AlterField(
            model_name='planillafabricacion',
            name='sala_pesaje',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='planillafabricacion',
            name='usuario_creacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='planillafabricacion',
            name='usuario_ultima_modificacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='registrofirma',
            name='firma_hash',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registrofirma',
            name='tipo_firma',
            field=models.CharField(choices=[('JEFE_SECCION', 'Jefe de Sección'), ('JEFE_PRODUCCION', 'Jefe de Producción'), ('INSPECTOR_CALIDAD', 'Inspector de Calidad'), ('QUIMICO_FARMACEUTICO', 'Químico Farmacéutico'), ('CONTROL_CALIDAD', 'Control de Calidad')], max_length=40),
        ),
        migrations.AlterField(
            model_name='rol',
            name='permisos',
            field=models.JSONField(default=list),
        ),
    ]
