# Generated by Django 5.2.8 on 2025-11-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0013_alter_jarabe_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planillaenvase',
            name='estado_aprobacion',
            field=models.CharField(choices=[('EN PROCESO', 'En proceso'), ('APROBADO', 'Aprobado')], default='EN PROCESO', max_length=20),
        ),
        migrations.AddField(
            model_name='planillaenvaseprimario',
            name='estado_aprobacion',
            field=models.CharField(choices=[('EN PROCESO', 'En proceso'), ('APROBADO', 'Aprobado')], default='EN PROCESO', max_length=20),
        ),
        migrations.AddField(
            model_name='planillafabricacion',
            name='estado_aprobacion',
            field=models.CharField(choices=[('EN PROCESO', 'En proceso'), ('APROBADO', 'Aprobado')], default='EN PROCESO', max_length=20),
        ),
    ]
