# Generated by Django 5.2.8 on 2025-11-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0014_planillaenvase_estado_aprobacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrofirma',
            name='tipo_firma',
            field=models.CharField(choices=[('JEFE_SECCION', 'Jefe de Sección'), ('JEFE_PRODUCCION', 'Jefe de Producción'), ('INSPECTOR_CALIDAD', 'Inspector de Calidad'), ('QUIMICO_FARMACEUTICO', 'Químico Farmacéutico')], max_length=40),
        ),
    ]
