# Generated by Django 5.2.8 on 2025-11-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0015_alter_registrofirma_tipo_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planillaenvase',
            name='estado_aprobacion',
            field=models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('APROBADO', 'Aprobado')], default='EN_PROCESO', max_length=20),
        ),
        migrations.AlterField(
            model_name='planillaenvaseprimario',
            name='estado_aprobacion',
            field=models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('APROBADO', 'Aprobado')], default='EN_PROCESO', max_length=20),
        ),
        migrations.AlterField(
            model_name='planillafabricacion',
            name='estado_aprobacion',
            field=models.CharField(choices=[('EN PROCESO', 'En proceso'), ('APROBADO', 'Aprobado')], default='EN_PROCESO', max_length=20),
        ),
    ]
