# Generated by Django 5.2.8 on 2025-11-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0016_alter_planillaenvase_estado_aprobacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='fecha_vencimiento_credenciales',
        ),
        migrations.AlterField(
            model_name='planillafabricacion',
            name='estado_aprobacion',
            field=models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('APROBADO', 'Aprobado')], default='EN_PROCESO', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrofirma',
            name='tipo_firma',
            field=models.CharField(max_length=40),
        ),
    ]
