# Generated by Django 5.2.8 on 2025-11-29 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0017_remove_usuariopersonalizado_fecha_vencimiento_credenciales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='estado_aprobacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='firma_inspector_calidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas_materia_prima', to='GPQAPI.registrofirma'),
        ),
        migrations.AddField(
            model_name='registrofirma',
            name='materia_prima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.materiaprima'),
        ),
    ]
