# Generated by Django 5.2.8 on 2025-11-30 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0019_remove_registrofirma_materia_prima_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlcalidad',
            name='batch_materia_prima',
        ),
        migrations.RemoveField(
            model_name='controlcalidad',
            name='cantidad_materia_prima',
        ),
        migrations.RemoveField(
            model_name='controlcalidad',
            name='estado_aprobacion',
        ),
        migrations.RemoveField(
            model_name='controlcalidad',
            name='nombre_materia_prima',
        ),
        migrations.RemoveField(
            model_name='controlcalidad',
            name='tipo_control',
        ),
        migrations.RemoveField(
            model_name='planillafabricacion',
            name='control_calidad_materia_prima',
        ),
        migrations.RemoveField(
            model_name='planillafabricacion',
            name='control_calidad_producto',
        ),
        migrations.AddField(
            model_name='planillafabricacion',
            name='control_calidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='planillas_fabricacion', to='GPQAPI.controlcalidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controlcalidad',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controlcalidad',
            name='resultado',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch', models.CharField(max_length=100)),
                ('control_calidad', models.BooleanField(default=False)),
                ('estado_aprobacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado')], default='PENDIENTE', max_length=20)),
                ('firma_inspector_calidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas_materia_prima', to='GPQAPI.registrofirma')),
            ],
        ),
        migrations.AddField(
            model_name='planillafabricacion',
            name='materia_prima',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.materiaprima'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrofirma',
            name='materia_prima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.materiaprima'),
        ),
    ]
