# Generated by Django 5.2.8 on 2025-11-30 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0020_remove_controlcalidad_batch_materia_prima_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planillafabricacion',
            name='materia_prima',
        ),
        migrations.RemoveField(
            model_name='registrofirma',
            name='materia_prima',
        ),
        migrations.RemoveField(
            model_name='planillafabricacion',
            name='control_calidad',
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='batch_materia_prima',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='cantidad_materia_prima',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='estado_aprobacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='nombre_materia_prima',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='tipo_control',
            field=models.CharField(choices=[('MATERIA_PRIMA', 'Materia Prima'), ('PRODUCTO_TERMINADO', 'Producto Terminado')], default='PRODUCTO_TERMINADO', max_length=20),
        ),
        migrations.AddField(
            model_name='planillafabricacion',
            name='control_calidad_materia_prima',
            field=models.ForeignKey(default=1, limit_choices_to={'tipo_control': 'MATERIA_PRIMA'}, on_delete=django.db.models.deletion.CASCADE, related_name='planillas_fabricacion_materia_prima', to='GPQAPI.controlcalidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planillafabricacion',
            name='control_calidad_producto',
            field=models.ForeignKey(default=1, limit_choices_to={'tipo_control': 'PRODUCTO_TERMINADO'}, on_delete=django.db.models.deletion.CASCADE, related_name='planillas_fabricacion_producto', to='GPQAPI.controlcalidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controlcalidad',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.producto'),
        ),
        migrations.AlterField(
            model_name='controlcalidad',
            name='resultado',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='MateriaPrima',
        ),
    ]
