# Generated by Django 5.2.8 on 2025-11-30 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0021_remove_planillafabricacion_materia_prima_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlcalidad',
            name='batch_materia_prima',
        ),
        migrations.RemoveField(
            model_name='controlcalidad',
            name='cantidad_materia_prima',
        ),
        migrations.RemoveField(
            model_name='controlcalidad',
            name='estado_aprobacion',
        ),
        migrations.RemoveField(
            model_name='controlcalidad',
            name='nombre_materia_prima',
        ),
        migrations.RemoveField(
            model_name='controlcalidad',
            name='tipo_control',
        ),
        migrations.RemoveField(
            model_name='planillafabricacion',
            name='control_calidad_materia_prima',
        ),
        migrations.RemoveField(
            model_name='planillafabricacion',
            name='control_calidad_producto',
        ),
        migrations.AddField(
            model_name='planillafabricacion',
            name='control_calidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='planillas_fabricacion', to='GPQAPI.controlcalidad'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch', models.CharField(max_length=100)),
                ('estado_aprobacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado')], default='PENDIENTE', max_length=20)),
                ('control_calidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_primas', to='GPQAPI.controlcalidad')),
            ],
        ),
        migrations.AddField(
            model_name='planillafabricacion',
            name='materia_prima',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.materiaprima'),
            preserve_default=False,
        ),
    ]
