# Generated by Django 5.2.8 on 2025-11-30 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0022_remove_controlcalidad_batch_materia_prima_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='control_calidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias_primas', to='GPQAPI.controlcalidad'),
        ),
    ]
