# Generated by Django 5.2.8 on 2025-11-30 01:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0023_alter_materiaprima_control_calidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcalidad',
            name='fecha_verificacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='control_calidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materias_primas', to='GPQAPI.controlcalidad'),
            preserve_default=False,
        ),
    ]
