# Generated by Django 5.2.8 on 2025-11-30 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0024_alter_controlcalidad_fecha_verificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlcalidad',
            name='firma_control_calidad',
        ),
        migrations.RemoveField(
            model_name='registrofirma',
            name='control_calidad',
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='firma_inspector_calidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles_calidad_firmados', to='GPQAPI.registrofirma'),
        ),
    ]
