# Generated by Django 5.2.8 on 2025-11-30 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0025_remove_controlcalidad_firma_control_calidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlcalidad',
            old_name='firma_inspector_calidad',
            new_name='firma_control_calidad',
        ),
    ]
