# Generated by Django 5.2.8 on 2025-11-30 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0026_rename_firma_inspector_calidad_controlcalidad_firma_control_calidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlcalidad',
            name='materia_prima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controles_calidad', to='GPQAPI.materiaprima'),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='firma_inspector_calidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas_materia_prima', to='GPQAPI.registrofirma'),
        ),
        migrations.AlterField(
            model_name='controlcalidad',
            name='fecha_verificacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='controlcalidad',
            name='firma_control_calidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas_cc', to='GPQAPI.registrofirma'),
        ),
        migrations.AlterField(
            model_name='controlcalidad',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controlcalidad',
            name='resultado',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='control_calidad',
            field=models.BooleanField(default=False),
        ),
    ]
