# Generated by Django 5.2.8 on 2025-11-30 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0027_controlcalidad_materia_prima_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planillafabricacion',
            name='balanza_numero',
        ),
        migrations.RemoveField(
            model_name='planillafabricacion',
            name='etiqueta_limpieza',
        ),
        migrations.RemoveField(
            model_name='planillafabricacion',
            name='liberacion_area',
        ),
        migrations.RemoveField(
            model_name='planillafabricacion',
            name='sala_pesaje',
        ),
    ]
