# Generated by Django 5.2.8 on 2025-11-30 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0028_remove_planillafabricacion_balanza_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlcalidad',
            name='inspector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='controles_a_firmar', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planillafabricacion',
            name='balanza_numero',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='planillafabricacion',
            name='etiqueta_limpieza',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planillafabricacion',
            name='liberacion_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planillafabricacion',
            name='sala_pesaje',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
