# Generated by Django 5.2.8 on 2025-11-30 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0029_controlcalidad_inspector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialEnvasePrimario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_envase', models.CharField(max_length=100)),
                ('codigo_calidad', models.CharField(blank=True, max_length=50, unique=True)),
                ('control_calidad', models.BooleanField(default=False)),
                ('estado_aprobacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado')], default='PENDIENTE', max_length=20)),
                ('firma_inspector_calidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas_material_envase_primario', to='GPQAPI.registrofirma')),
            ],
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='material_envase_primario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controles_calidad_envase_primario', to='GPQAPI.materialenvaseprimario'),
        ),
    ]
