# Generated by Django 5.2.8 on 2025-11-30 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0030_materialenvaseprimario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planillaenvaseprimario',
            name='balanza_numero',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='planillaenvaseprimario',
            name='firma_inspector_calidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firma_ic_envase_primario', to='GPQAPI.registrofirma'),
        ),
        migrations.AddField(
            model_name='planillaenvaseprimario',
            name='material_envase_primario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.materialenvaseprimario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planillaenvaseprimario',
            name='sala_pesaje',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
