# Generated by Django 5.2.8 on 2025-11-30 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0031_planillaenvaseprimario_balanza_numero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planillaenvaseprimario',
            name='materiales_json',
        ),
    ]
