# Generated by Django 5.2.8 on 2025-12-02 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0033_materialenvasesecundarioempaque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcalidad',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.producto'),
        ),
    ]
