# Generated by Django 5.2.8 on 2025-12-02 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0034_alter_controlcalidad_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcalidad',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.producto'),
            preserve_default=False,
        ),
    ]
