# Generated by Django 5.2.8 on 2025-12-02 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0036_alter_controlcalidad_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialenvaseprimario',
            name='firma_inspector_calidad',
        ),
        migrations.RemoveField(
            model_name='materialenvasesecundarioempaque',
            name='firma_inspector_calidad',
        ),
    ]
