# Generated by Django 5.2.8 on 2025-12-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0037_remove_materialenvaseprimario_firma_inspector_calidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planillaenvase',
            name='tipo_planilla',
            field=models.CharField(choices=[('PEDIDO_BODEGA', 'Pedido a Bodega'), ('PRODUCCION', 'Producción')], default='PRODUCCION', max_length=20),
        ),
        migrations.AddField(
            model_name='planillaenvaseprimario',
            name='tipo_planilla',
            field=models.CharField(choices=[('PEDIDO_BODEGA', 'Pedido a Bodega'), ('PRODUCCION', 'Producción')], default='PRODUCCION', max_length=20),
        ),
        migrations.AddField(
            model_name='planillafabricacion',
            name='tipo_planilla',
            field=models.CharField(choices=[('PEDIDO_BODEGA', 'Pedido a Bodega'), ('PRODUCCION', 'Producción')], default='PRODUCCION', max_length=20),
        ),
    ]
