# Generated by Django 5.2.8 on 2025-12-05 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0038_planillaenvase_tipo_planilla_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='planillaenvase',
            name='tipo_planilla',
        ),
        migrations.RemoveField(
            model_name='planillaenvaseprimario',
            name='tipo_planilla',
        ),
        migrations.RemoveField(
            model_name='planillafabricacion',
            name='tipo_planilla',
        ),
        migrations.CreateModel(
            name='MovimientoBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('referencia_documento', models.CharField(blank=True, max_length=100)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.bodega')),
                ('materia_prima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='GPQAPI.materiaprima')),
                ('material_envase_primario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='GPQAPI.materialenvaseprimario')),
                ('material_envase_secundario_empaque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='GPQAPI.materialenvasesecundarioempaque')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockEnvasePrimario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.bodega')),
                ('material_envase_primario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.materialenvaseprimario')),
            ],
            options={
                'unique_together': {('bodega', 'material_envase_primario')},
            },
        ),
        migrations.CreateModel(
            name='StockEnvaseSecundario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.bodega')),
                ('material_envase_secundario_empaque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.materialenvasesecundarioempaque')),
            ],
            options={
                'unique_together': {('bodega', 'material_envase_secundario_empaque')},
            },
        ),
        migrations.CreateModel(
            name='StockMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.bodega')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.materiaprima')),
            ],
            options={
                'unique_together': {('bodega', 'materia_prima')},
            },
        ),
    ]
