# Generated by Django 5.2.8 on 2025-12-05 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0039_bodega_remove_planillaenvase_tipo_planilla_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockenvaseprimario',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockenvaseprimario',
            name='bodega',
        ),
        migrations.RemoveField(
            model_name='stockenvaseprimario',
            name='material_envase_primario',
        ),
        migrations.AlterUniqueTogether(
            name='stockenvasesecundario',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockenvasesecundario',
            name='bodega',
        ),
        migrations.RemoveField(
            model_name='stockenvasesecundario',
            name='material_envase_secundario_empaque',
        ),
        migrations.RemoveField(
            model_name='bodega',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='stockmateriaprima',
            name='cantidad_actual',
        ),
        migrations.AddField(
            model_name='bodega',
            name='es_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bodega',
            name='tipo',
            field=models.CharField(choices=[('MP', 'Materia Prima'), ('EP', 'Envase Primario'), ('ES', 'Envase Secundario/Empaque'), ('PT', 'Producto Terminado')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmateriaprima',
            name='cantidad_disponible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockmateriaprima',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='stockmateriaprima',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_materia_prima', to='GPQAPI.bodega'),
        ),
        migrations.AlterField(
            model_name='stockmateriaprima',
            name='materia_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='GPQAPI.materiaprima'),
        ),
        migrations.CreateModel(
            name='StockMaterialEnvasePrimario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_envase_primario', to='GPQAPI.bodega')),
                ('material_envase_primario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='GPQAPI.materialenvaseprimario')),
            ],
            options={
                'unique_together': {('bodega', 'material_envase_primario')},
            },
        ),
        migrations.CreateModel(
            name='StockMaterialEnvaseSecundarioEmpaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_envase_secundario', to='GPQAPI.bodega')),
                ('material_envase_secundario_empaque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='GPQAPI.materialenvasesecundarioempaque')),
            ],
            options={
                'unique_together': {('bodega', 'material_envase_secundario_empaque')},
            },
        ),
        migrations.DeleteModel(
            name='MovimientoBodega',
        ),
        migrations.DeleteModel(
            name='StockEnvasePrimario',
        ),
        migrations.DeleteModel(
            name='StockEnvaseSecundario',
        ),
    ]
