# Generated by Django 5.2.8 on 2025-12-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0040_alter_stockenvaseprimario_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planillaenvaseprimario',
            name='proposito',
            field=models.CharField(choices=[('PRODUCCION', 'Producción'), ('PEDIDO_BODEGA', 'Pedido a Bodega')], default='PRODUCCION', max_length=20),
        ),
        migrations.AddField(
            model_name='planillafabricacion',
            name='proposito',
            field=models.CharField(choices=[('PRODUCCION', 'Producción'), ('PEDIDO_BODEGA', 'Pedido a Bodega')], default='PRODUCCION', max_length=20),
        ),
    ]
