# Generated by Django 5.2.8 on 2025-12-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0041_planillaenvaseprimario_proposito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('JEFE_SECCION', 'Jefe de Sección'), ('JEFE_PRODUCCION', 'Jefe de Producción'), ('INSPECTOR_CALIDAD', 'Inspector de Calidad'), ('QUIMICO_FARMACEUTICO', 'Químico Farmacéutico')], max_length=30),
        ),
        migrations.RemoveField(
            model_name='planillaenvaseprimario',
            name='proposito',
        ),
        migrations.RemoveField(
            model_name='planillafabricacion',
            name='proposito',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
