# Generated by Django 5.2.8 on 2025-12-05 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0042_alter_perfilusuario_rol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='cargo',
        ),
    ]
