# Generated by Django 5.2.8 on 2025-12-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0043_remove_perfilusuario_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planillaenvaseprimario',
            name='firma_inspector_calidad',
        ),
        migrations.RemoveField(
            model_name='planillafabricacion',
            name='firma_inspector_calidad',
        ),
        migrations.AddField(
            model_name='planillaenvaseprimario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('PRODUCCION', 'Producción'), ('PEDIDO_BODEGA', 'Pedido a Bodega')], default='PRODUCCION', help_text='Indica si el proceso es producción o un pedido a bodega', max_length=20),
        ),
    ]
