# Generated by Django 5.2.8 on 2025-12-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0044_remove_planillaenvaseprimario_firma_inspector_calidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planillafabricacion',
            name='tipo_movimiento',
            field=models.CharField(choices=[('PRODUCCION', 'Producción'), ('PEDIDO_BODEGA', 'Pedido a bodega')], default='PRODUCCION', max_length=20),
        ),
        migrations.AlterField(
            model_name='planillaenvaseprimario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('PRODUCCION', 'Producción'), ('PEDIDO_BODEGA', 'Pedido a bodega')], default='PRODUCCION', max_length=20),
        ),
    ]
