# Generated by Django 5.2.8 on 2025-12-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0045_planillafabricacion_tipo_movimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planillafabricacion',
            name='cantidad_entregada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
