# Generated by Django 5.2.8 on 2025-12-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0046_planillafabricacion_cantidad_entregada'),
    ]

    operations = [
        migrations.AddField(
            model_name='planillaenvaseprimario',
            name='cantidad_entregada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
