# Generated by Django 5.2.8 on 2025-12-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0047_planillaenvaseprimario_cantidad_entregada'),
    ]

    operations = [
        migrations.AddField(
            model_name='planillaenvaseprimario',
            name='batch_standart',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Batch Standart'),
        ),
        migrations.AddField(
            model_name='planillafabricacion',
            name='batch_standart',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Batch Standart'),
        ),
        migrations.AddField(
            model_name='planillafabricacion',
            name='cont_por_100ml',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cont. por 100 mL'),
        ),
    ]
