# Generated by Django 5.2.8 on 2025-12-07 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPQAPI', '0048_planillaenvaseprimario_batch_standart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanillaEnvaseSecundarioEmpaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(blank=True, max_length=100)),
                ('fecha_primera_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_ultima_modificacion', models.CharField(blank=True, max_length=100)),
                ('serie', models.CharField(max_length=50)),
                ('numero_planilla', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('batch_standart', models.CharField(blank=True, max_length=100, null=True, verbose_name='Batch Standart')),
                ('tipo_movimiento', models.CharField(choices=[('PRODUCCION', 'Producción'), ('PEDIDO_BODEGA', 'Pedido a bodega')], default='PRODUCCION', max_length=20)),
                ('rendimiento_teorico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodo_eficacia', models.IntegerField()),
                ('cantidad_estuches', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_entregada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado_aprobacion', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('APROBADO', 'Aprobado')], default='EN_PROCESO', max_length=20)),
                ('control_calidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.controlcalidad')),
                ('firma_jefe_produccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firma_jp_envase_secundario', to='GPQAPI.registrofirma')),
                ('firma_jefe_seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firma_js_envase_secundario', to='GPQAPI.registrofirma')),
                ('firma_quimico_farmaceutico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firma_qf_envase_secundario', to='GPQAPI.registrofirma')),
                ('material_envase_secundario_empaque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.materialenvasesecundarioempaque')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.producto')),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.tipoproducto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='registrofirma',
            name='planilla_envase_secundario_empaque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GPQAPI.planillaenvasesecundarioempaque'),
        ),
    ]
